# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import battery_data_service_pb2 as battery__data__service__pb2


class BatteryDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteUserBatteryData = channel.unary_unary(
                '/battery_data.BatteryDataService/DeleteUserBatteryData',
                request_serializer=battery__data__service__pb2.DeleteUserBatteryDataRequest.SerializeToString,
                response_deserializer=battery__data__service__pb2.DeleteUserBatteryDataResponse.FromString,
                )


class BatteryDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteUserBatteryData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BatteryDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteUserBatteryData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserBatteryData,
                    request_deserializer=battery__data__service__pb2.DeleteUserBatteryDataRequest.FromString,
                    response_serializer=battery__data__service__pb2.DeleteUserBatteryDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'battery_data.BatteryDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BatteryDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteUserBatteryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/battery_data.BatteryDataService/DeleteUserBatteryData',
            battery__data__service__pb2.DeleteUserBatteryDataRequest.SerializeToString,
            battery__data__service__pb2.DeleteUserBatteryDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
