# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battery_data_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62\x61ttery_data_service.proto\x12\x0c\x62\x61ttery_data\"/\n\x1c\x44\x65leteUserBatteryDataRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"Z\n\x1d\x44\x65leteUserBatteryDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0f\x64\x65leted_devices\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\x86\x01\n\x12\x42\x61tteryDataService\x12p\n\x15\x44\x65leteUserBatteryData\x12*.battery_data.DeleteUserBatteryDataRequest\x1a+.battery_data.DeleteUserBatteryDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battery_data_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DELETEUSERBATTERYDATAREQUEST']._serialized_start=44
  _globals['_DELETEUSERBATTERYDATAREQUEST']._serialized_end=91
  _globals['_DELETEUSERBATTERYDATARESPONSE']._serialized_start=93
  _globals['_DELETEUSERBATTERYDATARESPONSE']._serialized_end=183
  _globals['_BATTERYDATASERVICE']._serialized_start=186
  _globals['_BATTERYDATASERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
